import { spotifyApi } from "@/lib/spotify/api.ts";
import { TTrack } from "@/lib/store.ts";
import { ref } from "vue";
import { addAudioFeatures, cache } from "@/lib/spotify/cache.ts";

export const previousTracks = ref<Array<TTrack>>([]);
export const currentTrack = ref<TTrack>();
export const nextTracks = ref<Array<TTrack>>([]);

export async function syncQueue() {
    if (Object.values(cache.playlists).length) {
        const playlist = Object.values(cache.playlists)[0];

        currentTrack.value = playlist[Math.floor(Math.random() * playlist.length)];
        nextTracks.value = Array.from({ length: 6 }, () => playlist[Math.floor(Math.random() * playlist.length)]);
        previousTracks.value = Array.from({ length: 6 }, () => playlist[Math.floor(Math.random() * playlist.length)]);
        return;
    }

    //const temp = await spotifyApi("/me/player/currently-playing");
    const temp = { item: {
        "id": "2sX7lJXsOYGP1Us6CqM9t1",
        "name": "Little Bit of Love",
        "type": "track",
        "album": {
            "id": "0NZUGfUMwjt3bPlVHxnIN2",
            "name": "Little Bit of Love",
            "type": "album",
            "album_type": "single",
            "artists": [
                {
                    "id": "5SHxzwjek1Pipl1Yk11UHv",
                    "name": "Tom Grennan",
                    "type": "artist",
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/5SHxzwjek1Pipl1Yk11UHv"
                    },
                    "href": "https://api.spotify.com/v1/artists/5SHxzwjek1Pipl1Yk11UHv",
                    "uri": "spotify:artist:5SHxzwjek1Pipl1Yk11UHv"
                }
            ],
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "PR",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/0NZUGfUMwjt3bPlVHxnIN2"
            },
            "href": "https://api.spotify.com/v1/albums/0NZUGfUMwjt3bPlVHxnIN2",
            "images": [
                {
                    "height": 640,
                    "width": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273e415994ab2bc4df390ef1053"
                },
                {
                    "height": 300,
                    "width": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02e415994ab2bc4df390ef1053"
                },
                {
                    "height": 64,
                    "width": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851e415994ab2bc4df390ef1053"
                }
            ],
            "release_date": "2021-01-08",
            "release_date_precision": "day",
            "total_tracks": 5,
            "uri": "spotify:album:0NZUGfUMwjt3bPlVHxnIN2"
        },
        "artists": [
            {
                "id": "5SHxzwjek1Pipl1Yk11UHv",
                "name": "Tom Grennan",
                "type": "artist",
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/5SHxzwjek1Pipl1Yk11UHv"
                },
                "href": "https://api.spotify.com/v1/artists/5SHxzwjek1Pipl1Yk11UHv",
                "uri": "spotify:artist:5SHxzwjek1Pipl1Yk11UHv"
            }
        ],
        "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
        ],
        "disc_number": 1,
        "duration_ms": 226268,
        "explicit": false,
        "external_ids": {
            "isrc": "GBARL2001197"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/2sX7lJXsOYGP1Us6CqM9t1"
        },
        "features": {
            "id": "2sX7lJXsOYGP1Us6CqM9t1",
            "type": "audio_features",
            "acousticness": 0.0833,
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/2sX7lJXsOYGP1Us6CqM9t1",
            "danceability": 0.689,
            "duration_ms": 226268,
            "energy": 0.706,
            "instrumentalness": 0,
            "key": 1,
            "liveness": 0.105,
            "loudness": -4.48,
            "mode": 0,
            "speechiness": 0.0312,
            "tempo": 106.52,
            "time_signature": 4,
            "track_href": "https://api.spotify.com/v1/tracks/2sX7lJXsOYGP1Us6CqM9t1",
            "uri": "spotify:track:2sX7lJXsOYGP1Us6CqM9t1",
            "valence": 0.623
        },
        "href": "https://api.spotify.com/v1/tracks/2sX7lJXsOYGP1Us6CqM9t1",
        "is_local": false,
        "popularity": 59,
        "preview_url": "https://p.scdn.co/mp3-preview/d254f2af818bab3843a1de549ba19ac75dae62d3?cid=b28f8580eecf4b3aa9bd0c1a59fde6c8",
        "track_number": 1,
        "uri": "spotify:track:2sX7lJXsOYGP1Us6CqM9t1"
    } };
    const response = {
        currently_playing: temp.item,
        queue: [temp.item, temp.item, temp.item, temp.item, temp.item, temp.item, temp.item]
    };

    if (!currentTrack.value || currentTrack.value.id !== response.currently_playing.id) {
        if (currentTrack.value) {
            previousTracks.value.push(currentTrack.value);
        }

        currentTrack.value = response.currently_playing;
        nextTracks.value = response.queue;

        await addAudioFeatures([currentTrack.value, ...nextTracks.value]);
    }

    previousTracks.value.push(currentTrack.value); // temp
    previousTracks.value.push(currentTrack.value); // temp
}
